spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

neis:
  api-key: ${NEIS_API_KEY}

jwt:
  secret: ${JWT_SECRET:VlwEyVHeCcZuQeThWmYqTkPingKeOpQrStUvWxYz1234567890}
  expiration: ${JWT_EXPIRATION:86400000}

fastapi:
  base-url: http://${FAST_API_URL}:8001
  internal-token: ${FASTAPI_INTERNAL_TOKEN:}